---
abstract: 'allow old style CGI applications to use the plack streaming protocol'
author:
  - 'Torsten Förtsch <torsten.foertsch@gmx.net>'
build_requires:
  Test::More: '0.88'
configure_requires:
  Module::Build::Tiny: '0.036'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.141170'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Plack-App-CGIBin-Streaming
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  CGI::Compile: '0.17'
  PerlIO::via: '0.11'
  Plack: '0.9989'
  perl: '5.010'
resources:
  bugtracker: https://github.com/binary-com/perl-Plack-App-CGIBin-Streaming/issues
  homepage: https://github.com/binary-com/perl-Plack-App-CGIBin-Streaming
  repository: https://github.com/binary-com/perl-Plack-App-CGIBin-Streaming.git
version: '0.01'
x_contributors:
  - 'Rakesh Kumar Shardiwal <rakesh.shardiwal@gmail.com>'
  - 'Torsten Förtsch <torsten@binary.com>'
